#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: "2.0"
flavor: "Generic"
service:
  # name of the service:
  name: "PM Stats Query Service"
  # Design Country (set on the source products)
  design_countries:
    - HU                         # Hungary
  # Compilation Country (Set on the derivative products)
  sw_compilation_country: SE
  # Release responsible
  release_responsible: BCSDBECH
  #  Design responsible
  design_responsible: BCSDBECH
    # using "Completed" when encryption is not changed compared to previous released version.
    #  encryption_status: "Completed"
    # Bookmarks
    #  bookmark: PRIM
    # The documents is optional if all eridoc document revisions are set
  # documents:
    # Read documents revisions from this file
  # Use munin-adp generate-pri-input and pri.py to generate the file
  # Relative file path to product_structure.yaml
    # import: ../build/documents.yaml                                                # Part of Documentation side
  # Details of the APR product structure:
  top_product:
    alias: ["eric-oss-pm-stats-query-service"]
    # APR Product Number
    number: APR 201 640
    # Description
    description: "Query Service is a stateless microservice based on the Spring Boot Chassis. This service exposes data from a PostgreSQL database via OData (V4) queries."
    # Includes
    includes:
      # SUSE Licenses
      - prim: 1/FAL 115 3215
        rstate: R1A
      - prim: 3/FAL 115 3215
        rstate: R1A
      - prim: 5/FAL 115 3215
        rstate: R1A
      - prim: 7/FAL 115 3215
        rstate: R1A
  # Details of the Source product structure
  src_products:
    # Source Code Product
    - label: Source
      number: CAV 101 0231
  # Details of zero or more derivative product structures, use [] for zero
  derivative_products:
    # Label describing the product, must be unique per list item
    - label: "HELM"
      number: "CXD 101 270"
      alias: ["eric-oss-pm-stats-query-service"]
      derivedFrom:
        munin: CAV 101 0231
    - label: "IMAGE"
      number: "CXU 101 1310"
      description: "PM Stats Query Service"
      includes:
        # Common Base OS
        - munin: CXC 201 2032
          version: 4.1.0
          secondPartyProduct: "True"
        # Common Base OS Repo
        - munin: CXC 201 2031
          version: 4.1.0
          secondPartyProduct: "True"

      uses_foss:
        - dependencies_file: ./../generated/dependencies/dependencies-3pp.yaml                    #  Dependencies YAML
      #        - foss_usage: foss.usage.yaml                               #  FOSS Usage YAML
      #      uses_encryption:
      #        - import: encryptions.yaml                                  #  ENCRYPTIONS YAML
      derivedFrom:
        munin: CAV 101 0231