#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

import:
  common: common-properties.yaml

Kubesec:
  Product: "${common.helm-chart-name}" # Name of your product ( this is an optional parameter now, newly added for analytics )
  Product_contact: 'PDLEEASWAT@pdl.internal.ericsson.com'
  KubesecYAML:
    Scan: True
    armLinks:
      Links:
      valuesOverride:
  KubesecCluster:
    Scan: False
    KubeconfigFile: "admin.conf"
    namespace: ''