#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-pm-stats-query-service.name" . }}-secret
  labels:
  {{- include "eric-oss-pm-stats-query-service.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-pm-stats-query-service.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  username: {{ .Values.query.credentials.database.username | b64enc | quote }}
  password: {{ .Values.query.credentials.database.password | b64enc | quote }}