{{- $serviceMesh := include "eric-oss-pm-stats-query-service.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-pm-stats-query-service.global-security-tls-enabled" . | trim -}}

#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-pm-stats-query-service.fullname" . }}
  labels:
{{- include "eric-oss-pm-stats-query-service.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-pm-stats-query-service.annotations" . | nindent 4 }}
spec:
{{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-pm-stats-query-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type | quote }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
{{- include "eric-oss-pm-stats-query-service.container-labels" . | nindent 8 }}
      annotations:
{{- include "eric-oss-pm-stats-query-service.container-annotations" . | nindent 8 }}
    spec:
      {{- if include "eric-oss-pm-stats-query-service.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-pm-stats-query-service.pullSecret" . | quote}}
      {{- end }}
      serviceAccountName: {{ template "eric-oss-pm-stats-query-service.fullname" . }}
      securityContext:
        fsGroup: {{ include "eric-oss-pm-stats-query-service.fsGroup.coordinated" . }}
        {{ include "eric-oss-pm-stats-query-service.supplementalGroups" . }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            defaultMode: 493
            name: {{ include "eric-oss-pm-stats-query-service.name" . }}-configmap
        - name: log-control-configmap-volume
          configMap:
            name: {{ include "eric-oss-pm-stats-query-service.log-control-configmap.name" . }}
      containers:
        - name: eric-oss-pm-stats-query-service
          image: {{ template "eric-oss-pm-stats-query-service.mainImagePath" . }}
          imagePullPolicy: {{ template "eric-oss-pm-stats-query-service.registryImagePullPolicy" . }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.lifecycle.preStop.command }}
          securityContext:
            {{- include "eric-oss-pm-stats-query-service.seccomp-profile" . | indent 12 }}
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 40514
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - name: config-volume
              mountPath: /config
            - name: log-control-configmap-volume
              mountPath: "/logcontrol"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "successThreshold") }}
            {{ print "successThreshold: " (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "successThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-pm-stats-query-service" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: /actuator/health/readiness
              port: http
          env:
          - name: SERVICE_ID
            value: {{ include "eric-oss-pm-stats-query-service.name" . | quote }}
          - name: JAVA_OPTS
            value: {{ include "eric-oss-pm-stats-query-service.jvmHeapSettings" . }}
          - name: LOG_CTRL_FILE
            value: {{ .Values.log.logControlFile  | quote }}
          - name: TZ
            value: {{ template "eric-oss-pm-stats-query-service.timezone" . }}
          {{ with index .Values "query" }}
          {{- if and (eq $serviceMesh "true") (eq $tls "true") }}
          - name: POSTGRES_USER
            value: {{ .credentials.roUserName | quote }}
          - name: POSTGRES_PASSWORD
            value: ""
          {{- else }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .credentials.kubernetesSecretName | quote }}
                key: {{ .credentials.keyForUserId | quote }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .credentials.kubernetesSecretName | quote }}
                key: {{ .credentials.keyForUserPw | quote }}
          {{- end }}
          - name: DATABASE_URL
            value: {{ .database.url | quote }}
          - name: DATASOURCE_ENABLED
            value: {{ .database.enabled | quote }}
          - name: KAFKA_ENABLED
            value: {{ .kafka.enabled | quote }}
          {{- end }}
          - name: POSTGRES_RETRY_BACKOFF_PERIOD
            value: {{ .Values.retry.postgres.maxAttempts | quote }}
          - name: POSTGRES_MAX_RETRY_ATTEMPTS
            value: {{ .Values.retry.postgres.maxAttempts | quote }}
          - name: POSTGRES_CONFIG
            value: {{ template "eric-oss-pm-stats-query-service.jdbc-config" . }}
          - name: KAFKA_CONSUMER_BOOTSTRAP_SERVER
            value: {{ include "eric-oss-pm-stats-query-service.kafka-bootstrap-server" . | quote }}
      {{- if .Values.global }}
        {{- if .Values.global.security }}
          {{- if .Values.global.security.tls }}
            {{- if .Values.global.security.tls.enabled }}
          - name: CONNECT_MODE
            value: "tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
          - name: TLS_MODE
            value: "only_tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
          - name: TLS_CA
            value: "ca_path"
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- include "eric-oss-pm-stats-query-service.loggingEnv" . | indent 10 }}
      {{- include "eric-oss-pm-stats-query-service.dstEnv" . | indent 10 }}
          resources:
            requests:
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-pm-stats-query-service" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-pm-stats-query-service" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
      nodeSelector: {{ include "eric-oss-pm-stats-query-service.nodeSelector" . | nindent 6 -}}

      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds:
        {{- include "eric-oss-pm-stats-query-service.terminationGracePeriodSeconds" . | nindent 8 }}
      {{- end }}

      {{ if .Values.tolerations }}
      tolerations: {{ include "eric-oss-pm-stats-query-service.merge-tolerations" . | nindent 8 }}
      {{ else if .Values.global }}
        {{ if .Values.global.tolerations }}
          tolerations: {{ include "eric-oss-pm-stats-query-service.merge-tolerations" . | nindent 8 }}
        {{ end }}
      {{ end }}

      {{- if (index .Values "podPriority" "eric-oss-pm-stats-query-service" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "eric-oss-pm-stats-query-service" "priorityClassName") }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints.deployment }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "eric-oss-pm-stats-query-service.name" . }}
            topologyKey: {{ .Values.affinity.topologyKey }}
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "eric-oss-pm-stats-query-service.name" . }}
              topologyKey: {{ .Values.affinity.topologyKey }}
      {{- end }}
