#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.autoScaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "eric-oss-pm-stats-query-service.fullname" . }}
  labels:
  {{- include "eric-oss-pm-stats-query-service.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-pm-stats-query-service.annotations" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "eric-oss-pm-stats-query-service.fullname" . }}
  minReplicas: {{ .Values.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  metrics:
  {{- if .Values.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoScaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoScaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
