#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if ne (.Values.replicaCount | int) 1 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-oss-pm-stats-query-service.name" . }}
  labels:
    {{- include "eric-oss-pm-stats-query-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-query-service.annotations" . | nindent 4 }}
spec:
{{- include "eric-oss-pm-stats-query-service.pod-disruption-budget" . | indent 2}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-pm-stats-query-service.name" . }}
{{- end -}}
