global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: query-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - '172.17.0.1:8080'