#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: datasource-secret
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "1"
type: Opaque
stringData:
  metrics-pwd: 'metricspwd'
  metrics-user: 'metricsuser'
  custom-pwd: 'custompwd'
  replica-pwd: 'replicapwd'
  replica-user: 'replicauser'
  super-pwd: 'superpwd'
  custom-user: 'customuser'